### ISSUE TITLE
API. Ознакомиться с JSON:API и описать API сервиса генерации документов

### ISSUE THREAD

**Issue by brshpl** [ag-students/support-service#4]
Посмотреть доку JSON:API и статью на Хабре (https://habr.com/ru/company/oleg-bunin/blog/433322/)
Продумать то, какие запросы будет принимать сервис генерации документов и как на них отвечать

**Comment by pushkinvladislav** [comment]
//Запрос:
http://localhost:4000/generate [POST]
 
{   "uid_user" : "674373763456",
    "surname" : "Иванов",
    "name" : "Иван",
    "patronymic" : "Иванов",
    "gender": "female",
    "birthday": "2000-06-13T06:02:24.633288Z",
    "home_adress" : "Москва, Красная 10",
    "vaccine" : "Гам-КОВИД-Вак",
    "first_dose_date" : "2000-06-13T06:02:24.633288Z",
    "second_dose_date" : "2000-06-13T06:02:24.633288Z"
}

//Ответ:

{
    "CreatedAt": "2021-06-13T06:02:24.633288Z",
    //возвращаем ссылку на pdf, сгенерированную на основе переданных данных
}
